# Generated by Django 3.0.6 on 2020-05-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20200511_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(default=False, verbose_name='Approaches'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(default=False, verbose_name='Chasing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(default=False, verbose_name='Climbing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(default=False, verbose_name='Eating'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(default=False, verbose_name='Foraging'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(default=False, verbose_name='Indifferent'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(default=False, verbose_name='Kuks'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(default=False, verbose_name='Moans'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_activity',
            field=models.CharField(default=None, max_length=50, verbose_name='Other_activity'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(default=False, verbose_name='Quaas'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(default=False, verbose_name='Running'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(default=False, verbose_name='Runs_from'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(default=False, verbose_name='Tail_flags'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.BooleanField(default=False, verbose_name='Tail_twitches'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='color',
            field=models.CharField(choices=[('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Gray', 'Gray')], default=None, max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('None', 'None')], default=None, max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default=None, max_length=50, verbose_name='Shift'),
        ),
    ]
