# Generated by Django 3.0.6 on 2020-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20200512_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='other_activity',
            new_name='other_activities',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='location',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('None', 'None')], default=None, max_length=50, verbose_name='Age'),
        ),
    ]
